### ISSUE TITLE
Loading a dataset from HDF5 file should construct original AnalysisResults object

### ISSUE THREAD

**Issue by GABowers** [VespucciProject/Vespucci#55]
Opened an h5 dataset in Vespucci, containing one result of univariate analysis. Attempted Univariate>Concatenate, but nothing showed up. Did another "univariate analysis" which DID show up. Saved dataset, closed, then opened again. Neither analysis showed up when Univariate>Concatenate was selected.

Vespucci file too large to attach here, but should be repeatable.

**Comment by dpfoose** [comment]
This is because they're is no distinction between AnalysisResults subclasses in the saved file. All analysis results look the same in the HDF5 file. This is by design, but I don't have a good reason to not implement it in a way that works. I'll consider this a feature request. This will still not work on datasets saved before the feature. It will appear in beta 2.

**Comment by dpfoose** [comment]
Greg's goal was fixed using metadata in the AnalysisResults object. Univariate results will still be initialized generically on save...
